workflows:
  build-android:
    name: Build Android APK
    instance_type: mac_mini_m2 # أو أي نوع آلة بناء تفضله
    scripts:
      - name: Clean Flutter project
        script: flutter clean
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK with Flutter
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
