workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable

    scripts:
      - name: Clean Flutter project
        script: flutter clean

      - name: Get Flutter packages
        script: flutter pub get

      - name: Build Android APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com  # يمكنك تغيير هذا إلى بريدك الإلكتروني
