workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    # تفعيل التخزين المؤقت لتسريع البناء
    cache:
      cache_paths:
        - ~/.pub-cache          # مكتبات Dart و Flutter
        - ~/.gradle/caches      # مكتبات Android

    environment:
      flutter: stable

    scripts:
      - name: Clean Flutter project
        script: flutter clean

      - name: Get Flutter packages
        script: flutter pub get

      - name: Build Android APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com  # استبدل هذا ببريدك الإلكتروني
