name: maker_exampapers
description: "تطبيق توليد أوراق اختبارات الطلاب"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # المكتبات الأساسية للمشروع المحدث
  excel: ^4.0.0
  pdf: ^3.10.4
  file_picker: ^6.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # حزم ملف الخط بالاسم والامتداد الصحيح تماماً
  assets:
    - assets/fonts/Cairo_Regular.ttf

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo_Regular.ttf
