name: maker_exampapers
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  excel: ^4.0.0
  pdf: ^3.10.4
  printing: ^5.11.1
  permission_handler: ^11.3.1    # تمت الإضافة
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Cairo-Regular.ttf
