org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false

# إلغاء الحظر الصارم للـ Namespaces المتكررة في مكتبات ML/TFLite القديمة
android.disableMinifyLocalDependenciesForLibraries=true
android.experimental.r8.dex-shrunk-desugared-library=true
